### ISSUE TITLE
Bug while running Example_INSA_Toulouse

### ISSUE THREAD

**Issue by s-martiz** [Art-Ev/ICEtool#10]
Dear ICE-tool community,
I'm wondering why I cannot run the Shadow Generator of UMEP from the example project Example_INSA_Toulouse.
I followed Step_1 and Step_2 without any problem. Concerning Step_3, I can only acces "Wikimedia Map" from the scrolling menu...
Any idea ?

Best regards
Simon Martinez 

![image](https://user-images.githubusercontent.com/50947346/169265551-5d829616-bcc3-455e-92b5-3181f6179e6a.png)

**Comment by SebastienPouchoulin** [comment]
Hi,
Once you have launched Step_2, 2 raster files are created in this folder (one for the trees, one for the buildings). You have to ad them as "layer>ad a layer> ad a raster layer" and choose the two files you just have created.
Then they should appear in the possible choices for Step_3.
(If you have any idea about my own issue I would appreciate)
Kind regards

**Comment by Art-Ev** [comment]
Hi !

As @SebastienPouchoulin explained, you first need to import the two files generated using Step 2 into your QGIS project.
In both the English and French manuals, the last sentence of step 2 (before "advanced user"), is bold and indicates that you must load the files before Step 3😛 

Small tip: to import these files you can simply drag'n drop them into qgis window

If issue is solved you can close it @simonmarti1992 ^^
