### ISSUE TITLE
Erreur Step_4

### ISSUE THREAD

**Issue by Apgl-64** [Art-Ev/ICEtool#11]
**Describe the bug**
2022-06-30T17:23:16     CRITICAL    Traceback (most recent call last):
              File "C:\Users/Guillaume.Pommier/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ICEtool\Scripts\Step4_ComputeTemperatureEPW.py", line 190, in processAlgorithm
              other_hours=pd.read_csv(last_saved,sep=',')
             UnboundLocalError: local variable 'last_saved' referenced before assignment
             

**To Reproduce**
Steps 4, même erreur avec .epw et .csv

**Question**
Est-ce que ça vient du script ou du format des fichier ETP et Weather?

 - OS: [Windows]
 - QGIS version [3.22.6-Białowieża]

**Comment by Art-Ev** [comment]
Bonjour,

A priori je dirai plutôt que l'étape 3 n'a pas été réalisée convenablement voir pas du tout (aucun fichier .tif d'ombre dans le dossier "Step_3")

**Comment by Apgl-64** [comment]
Effectivement les fichiers d'ombre étaient dans le dossier racine du projet et pas dans le dossier Step_3
Merci de votre aide
