### ISSUE TITLE
Temperature on the roof of buildings

### ISSUE THREAD

**Issue by diouck** [Art-Ev/ICEtool#14]
Hello,
I would like to know why the roof of the buildings is not taken into account in the calculation? Is it possible and how to integrate building roof materials? thank you for your understanding

**Comment by Art-Ev** [comment]
Hi,

The temperature of the roof varies a lot depending on the building (equipment, insulation, uses, etc.), the plugin being centred on the public space it was decided not to burden the tool with such a different thermal model (and all necessary inputs)

If you are looking for an open source tool for thermal modelling of buildings, I recommend to check LadyBug :
https://www.ladybug.tools/

**Comment by diouck** [comment]
thank you!
