### ISSUE TITLE
Influence of an elevated surface

### ISSUE THREAD

**Issue by Val-Antn** [Art-Ev/ICEtool#15]
Hi !
I need to model a planted surface (grass and trees) which is 3-4m higher than the surrounding ones. Is there a way to do that?
Should I model a building with trees and a ground surface over it? 
Should I simply consider that the surface is also at level zero?

The planted surface is on the left:
<img width="1368" alt="Capture d’écran 2022-12-13 à 10 54 05" src="https://user-images.githubusercontent.com/120457641/207285805-fe5fbe7e-7271-4962-97fd-638323c31180.png">

Thanks in advance for your help,

**Comment by Art-Ev** [comment]
Hi @Val-Antn !

In fact, this is evasively mentioned in the user manual as it may require very "GIS" skills. (and so maybe a little help from a colleague in your case)

Quick version, it's done between steps 2 and 3: you have to add topo to the building_terrain raster before shadow calculation. To do this, we use the raster calculator to add a DTM (for example for Montbrison: the RGE Alti of the IGN). You can also build you own topo raster from a vector layer.
