### ISSUE TITLE
Project creation and setup

### ISSUE THREAD

**Issue by derrieni** [Art-Ev/ICEtool#16]
Hello, I am experiencing ICETool and I want to do some attempt. Do I need to provide the layers study_area, buildings, trees and ground by myself ? Or if I want to calculate UHI on a specific city can I just import from opensource database files relative to my city ?

**Comment by Art-Ev** [comment]
Hello, 

Short answer : first check the documentation directly included in the plugin.

Long anwser : it depends. Depending on the layer and your geographical area of study. 
- Buildings layer can be created using OSM if sufficiently completed or local data (ex. BD Topo in France). 
- Tree layer : OSM or local data (if exist it's often at city scale and not at national level)
- Ground ; given the precision requested you will probably have to complete it yourself
