### ISSUE TITLE
Toiture végétalisée et rendu graphique

### ISSUE THREAD

**Issue by mcourchinoux** [Art-Ev/ICEtool#18]
Bonjour,
Je suis en train de découvrir et de prendre en main le plug in ICE Tool (merci pour ce travail et pour le PDF tutoriel étape par étape !)
J'ai bien finalisé l'étape 4 et j'arrive au résultat suivant (pièce jointe)
Ce qui m'amène à deux questions :

![image](https://user-images.githubusercontent.com/131249929/233024151-9dc03a71-721e-434a-985e-5e873d54abd5.png)

J'ai un projet avec des toitures terrasses végétalisées. Or j'ai l'impression que je ne peux pas superposer un bâtiment et une couche de sol (pelouse). Y'a-t-il un moyen de prendre en compte à la fois mon bâtiment et donc sa hauteur qui impacte les ombrages projetés sur le terrain, et la végétalisation en toiture ?

![image](https://user-images.githubusercontent.com/131249929/233024096-772fe433-0ef0-4741-9afa-c726bda3e94c.png)
Comment obtenir un résultat visuel plus "smooth" tel que présenté dans la fiche du plug-in ? Pour l'instant j'ai quelque chose de très graduel. 

Merci d'avance pour vos réponses détaillées (je découvre Qgis en même temps que ICE tool)

**Comment by Art-Ev** [comment]
Bonjour,

Concernant la partie ICEtool, cad la **toiture végétalisée** : le modèle utilisé ne permet pas de faire une modélisation thermique de la toiture car il faudrait alors faire un bilan thermique du bâtiment situé en dessous (et donc en renseigner les caractéristiques comme les usages). ICEtool se focalise uniquement sur l'espace public/extérieur en dehors du bâti et en ce sens l'évapotranspiration sur le toit aurait un impact négligeable sur les températures "au sol".
Pour faire ce genre d'analyse thermique il faudra plutôt se tourner vers des outils comme <https://www.ladybug.tools/> (si on veut rester dans le milieu de l'opensource). Pour prendre en compte la toiture végétalisée dans les analyses non thermiques d'ICEtool (Cr et CBS) il suffit de faire les ajustements directement au sein de la couche bâtiment.

Pour la représentation des résultats il s'agit plus d'un blocage lié à l'utilisation d'un SIG (ici QGIS) que d'ICEtool : ICEtool génère les résultats sous la forme de données vecteurs (des points liés à une table de données, ici toutes les températures au cours de la journée). Il s'agit des points utilisés pour la modélisation thermique, il n'y a donc pas de valeur "entre" ces points. 
Pour faire "plus joli" on peut par exemple générer une données raster (grossièrement : des valeurs "partout", comme une image). Pour cela on peut utiliser une des fonctions d'interpolation de QGIS (les valeurs entre les points d'ICEtool seront donc estimées sans bilan thermique, sur la base des températures des points autours). 

**Attention** : dans ce cas le résultat ne peut pas contenir toutes les informations générées par ICEtool (qui sont elles toutes bien présentes dans les données vecteurs) il faudra donc choisir (température à une heure donnée, min, moy, max ?)

**Comment by mcourchinoux** [comment]
Bonjour Arthur,

Tout d’abord merci pour votre réponse à ma question !
J’ai plusieurs interrogations concernant votre réponse :
-	« le toit aurait un impact négligeable sur les températures "au sol" » : Cela signifie que la mise en œuvre d’une toiture végétalisée sur l’ensemble de mon projet par rapport à une toiture terrasse béton classique n’améliore pas significative la réduction du phénomène d’ilôt de chaleur à l’échelle de ma parcelle ?
-	Concernant le bilan thermique, nous avons déjà réalisé sur un autre logiciel (Pléiades pour ne pas le citer) les simulations thermiques dynamiques et calcul réglementaire de notre projet. Comment intégrer les résultats de ces études au sein de la couche bâtiment ? Y’a-t-il une aide (manuel/tuto) décrivant cette action ?
-	J’en profite également pour vous demander s’il est possible de saisir l’albédo de nos bâtiments quelque part.

Merci pour votre retour sur le rendu graphique, j’ai pu améliorer ce point-là !
