### ISSUE TITLE
Questionnements autour d'un rendu graphique "lisse"

### ISSUE THREAD

**Issue by Wanair** [Art-Ev/ICEtool#19]
Bonjour,

Après m'être approprié l'outil, je me pose maintenant la question de la représentation graphique pour faire des sorties carto.

Sur un projet que j'ai simulé, j'obtiens bien une représentation brute une saccadée comme celle sur une des pages du site elioth.com :

![IT_Capture1](https://user-images.githubusercontent.com/131349009/233313331-02eb68d7-4d40-4f32-8156-ddc243ba3575.JPG)

En termes de qualité de rendu disons, j'ai trouvé, toujours sur le site, une représentation, plus "lisse" :

![IT_Capture2](https://user-images.githubusercontent.com/131349009/233313354-ba45b85e-d0a5-4e76-91cf-8a4474d020b7.JPG)

Je voulais m'assurer que le passage à cette représentation plus lisse se faisait bien par une symbologie "carte de chaleur" et non plus "graduée" comme sur la première ? En tout cas, je n'ai pas réussi à obtenir quelque chose de plus "lisse" sans passer par la symbo "carte de chaleur" sauf erreur de ma part ?

De là, découle une autre question : comment obtenir la légende en température de surface à droite ? Car la symbologie en carte de chaleur ne permet visiblement pas de l'obtenir en l'état. Doit-on la calculer d'une manière ou d'une autre ?

Sur un projet à partir duquel je me suis approprié l'outil, j'obtiens, lorsque j'utilise la symbologie "carte de chaleur", la carte suivante :

![IT_Capture3](https://user-images.githubusercontent.com/131349009/233314330-88092025-1f9a-4da9-9d47-be850cedc2e0.JPG)

En passant en mode carte de chaleur, cela donne une température à la fois aux bâtiments (globalement le bleu de la zone d'étude) et à l’extérieur de la zone d'étude (bleu). Ce n'est pas le cas en représentation graduée. Est-ce normal ? J'ai alors l'impression qu'à ces éléments sont donnés une température basse par défaut de surcroît.

Merci d'avance pour l'aide apportée.

**Comment by Art-Ev** [comment]
Bonjour,

Petit doublon avec #18, pas de soucis : 

A priori la fonction carte de chaleur ne donnera pas le resultat recherché. La fonction carte de chaleur évalue juste une aire d'influence par rapport à un poids donné. Entre deux points on aura donc une "valeur" plus faible que celle des deux points, exemple :
![CarteChaleur](https://user-images.githubusercontent.com/83211842/234643884-c6677779-dfd2-4118-ad57-c23d4376a79a.png)

Pour un rendu plus "lisse" on peut, par exemple, faire une interpolation avec QGIS. Attention, on perd alors une grosse partie de l'information qui sort de la modélisation thermique et il faut garder en tête que les valeurs "entre points" sont simplement interpolées (pas issues d'un bilan thermique sur 24h). Explications plus longues dans l'issue #18
