### ISSUE TITLE
Compréhension de la représentation cartographique et questionnement sur l'obtention de plusieurs carte en fonction de l'heure d'une même journée

### ISSUE THREAD

**Issue by Wanair** [Art-Ev/ICEtool#20]
Bonjour,

Afin d'asseoir ma compréhension de l'outil maintenant que j'ai pu me faire la main sur le plugin sur un projet, voici mes interrogations : 

Que représente une carte comme celle ci-dessous : 

![IT_Capture1](https://user-images.githubusercontent.com/131349009/233315786-7fdcbe08-3222-4db9-a47b-76aaffcee3c7.JPG)

Cela représente la moyenne des températures sur une journée ? Le max ? car l'outil calcul les deux et je suis pris d'un doute sur la donnée d'entrée.

- Comment ont été produite les cartes à des horaires précis de la journée comme on peut le voir sur ce lien en milieu de page avec les cadrants d'horloge qui évoluent au cours de la journée ? https://elioth.com/ice-la-solution-pour-etudier-le-rafraichissement-de-vos-quartiers/

Est-ce au moment du step 3 ou 4 de l'outil qu'il faut renseigner, au-delà de la date, un intervalle de temps resserré ? Mais je ne vois pas où exactement.

Merci d'avance de l'éventuel retour.

**Comment by Art-Ev** [comment]
Rebonjour,

Ici je pense que le soucis se situe dans la méconnaissance de QGIS (plus précisément de la symbologie ici) et pas forcément d'ICEtool. Si besoin, les exercices du manuel de QGIS sont très bien fait 😄  : https://docs.qgis.org/3.28/fr/docs/training_manual/basic_map/symbology.html

La carte peut représenter n'importe quelle information parmi celles générées en sortie d'ICEtool, cad pour chaque point (elles figurent également dans le manuel utilisateur FR & EN 📜 ) : 
- Températures heure par heure sur 24h (pour la journée sélectionnée lors du calcul)
- Température minimum (calculée à partir des températures au cours de la journée, simplement pour pré-macher le travail d'analyse)
- Température moyenne (idem)
- Température maximale (idem)
En sortie il me semble que la symbologie appliquée par défaut se fait sur le maximum.

Pour la réalisation des GIF ça se fait directement avec QGIS grâce à la gestion temporelle 🕥 .

**Comment by Wanair** [comment]
Bonjour, je me permets de relancer ce sujet pour pouvoir réaliser ce fameux GIF.

Comment faire en sorte que ce GIF soit basé sur les 24h de la journée dans la mesure où les 24 données pour chaque points sont stockées dans un tableau qui lui même est dans un champ ?
A l'heure actuelle, je n'arrive pas à récupérer tout cela pour faire quelque chose de dynamique.

Merci d'avance
