### ISSUE TITLE
ICE TOOL_the horizontal spacing is too big for covered area.

### ISSUE THREAD

**Issue by Leonor80** [Art-Ev/ICEtool#21]
i have a problem on icetool step 4
the horizontal spacing is too big for covered area.

Can anyone help me?

![MicrosoftTeams-image (1)](https://github.com/Art-Ev/ICEtool/assets/133341043/e23ea18a-37d2-4a3e-b0db-03f451f4088c)

**Comment by Art-Ev** [comment]
Solved by user (project input data were incomplete)
