### ISSUE TITLE
icetool_step 4 the horizontal spacing is too big for covered area.

### ISSUE THREAD

**Issue by Leonor80** [Art-Ev/ICEtool#22]
Hello 
i have a problem on icetool step 4 the horizontal spacing is too big for covered area.  Can anyone help me?

![MicrosoftTeams-image (1)](https://github.com/Art-Ev/ICEtool/assets/133341043/166b5e7e-0618-4b5a-9229-625f8a2ddec4)

**Comment by Art-Ev** [comment]
Duplicate with #21
