### ISSUE TITLE
Help to Icetool - properties table csv Material_DataBase

### ISSUE THREAD

**Issue by Leonor80** [Art-Ev/ICEtool#24]
Dear all,

We need a definiton of the follow thermic properties to modeling :

EP=
KC=
Lambd=

Thanks

**Comment by Art-Ev** [comment]
Hi,

These are different thermal properties of materials, here they are used for heat storage, evapotranspiration & conduction. To fully understand ICEtool thermal balance and modeling you need a set of notions in heat exchange.

We are currently building a set of procedures to mesure all these thermal properties and facilitate the addition of new materials to the database. Once this work finalised and published it will still be necessary to use expensive and specific equipment...
