### ISSUE TITLE
Aide pour résoudre erreur step 4

### ISSUE THREAD

**Issue by mcollet02** [Art-Ev/ICEtool#25]
Bonjour,

Je découvre le plugin ICEtool dans le cadre d'un projet école ingénieur en autonomie.
Arrivée à step 4, le calcul final me donne une erreur: il semble qu'il ne reconnait pas les colonnes 'alb','lambd','Cv' ... du csv Material_database. Les entêtes des colonnes du csv portent pourtant bien ces noms. Y a t il quelque chose à modifier ?

![erreur qgis icetool](https://github.com/Art-Ev/ICEtool/assets/134493352/188a0984-906e-4e8b-a3da-943cd302a33e)

Auriez vous une idée quant à l'origine de ce problème ?

Merci par avance.

 - QGIS version [3.22.7]

**Comment by Art-Ev** [comment]
Bonjour,

Est-ce qu'il serait possible de joindre le dossier projet (=les fichiers) correspondant au message d'erreur ? (beaucoup de possibilités)

Si je me base sur les erreurs les plus courantes je dirai que : 
- Le projet à été démarré de zéro sans utiliser la fonction "création de nouveau projet"
OU
- Le paramétrage de la couche "ground" a été modifié ou supprimé/recréé

Est-ce que le projet exemple sur le campus de l'INSA fonctionne ?

**Comment by mcollet02** [comment]
Bonjour,

Merci pour votre retour. Je n'avais pas fait attention au projet exemple, et suite à votre réponse, j'ai repris le projet et ce qui n'allait pas. Mon projet fonctionne enfin après de nombreuses tentatives, il s'agissait simplement d'une mauvaise manipulation de ma part, je ne maîtrise pas encore QGIS autant que je le souhaiterai !

Bonne continuation.
