### ISSUE TITLE
Problème d'exécution Etape 3

### ISSUE THREAD

**Issue by Orlenaafk** [Art-Ev/ICEtool#26]
Bonjour,

Passé l'étape 2, nous avons un message d'erreur pour l'étape 3 ou nous avons ce message d'erreur 

```
Traceback (most recent call last):
              File "C:\Users/Albert LEROY/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ICEtool\Scripts\ShadowGenerator\shadow_generator.py", line 262, in start_progress
              dsm = gdal_dsm.ReadAsArray().astype(np.float)
              File "C:\PROGRA~1\QGIS32~1.10\apps\Python39\lib\site-packages\numpy\__init__.py", line 284, in __getattr__
              raise AttributeError("module {!r} has no attribute "
             AttributeError: modul
```

Nous pensons que cela vient du plugin de votre outil car avec une ancienne version de QGIS cela marche très bien mais sur la nouvelle de QGIS : 3.28.10-Firenze

Comment pouvons nous faire ? Merci

**Comment by Art-Ev** [comment]
Bonjour,

Il y a du avoir maj d'un autre outil/plugin QGIS au passage qui a lui même mis à jour la librairie numpy.
Comme le message d'erreur posté ici est incomplet (manque la fin de la dernière ligne), j'ai créé un correctif "à l'aveugle" en allant chercher les modifications apportés par une maj potentielle de numpy.

A priori le problème devrait être corrigé avec la v1.4.1 (si c'est bien celui-ci), mais à confirmer vu que je n'ai pas le soucis. La nouvelle version est en cours de relecture par l'équipe de QGIS : en attendant qu'elle soit disponible directement depuis QGIS, il est possible de la télécharger depuis la page principale du github (release 1.4.1) et de l'installer manuellement avec QGIS ("installer depuis un zip").

(j'en ai profité pour ajouter les modifications non publiées dont un peu plus de pré-paramétrage pour le calcul des ombres)

@Orlenaafk, dites moi si la 1.4.1 règle le problème. Si non, pourriez-vous me donner la fin du message d'erreur et me dire quelle version de numpy utilise votre installation ? (récupérable par exemple via la fonction pip list : https://pip.pypa.io/en/stable/cli/pip_list/)

**Comment by laetitia-bos** [comment]
Bonjour, 

J'ai le même problème à l'étape 3. J'ai essayé d'installer le ZIP mis à jour pour régler le problème, mais j'obtiens ce message d'erreur : ModuleNotFoundError: No module named 'ICEtool-1' 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~1.8/apps/qgis-ltr/./python\qgis\utils.py", line 401, in loadPlugin
    __import__(packageName)
  File "C:\PROGRA~1/QGIS32~1.8/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'ICEtool-1'

Je ne peux donc pas installer la nouvelle version

**Comment by Art-Ev** [comment]
@laetitia-bos, Github avait renommé un dossier. J'ai ajouté un fichier zip à la release ([ICEtool-1.4.1.zip](https://github.com/Art-Ev/ICEtool/releases/download/v1.4.1/ICEtool-1.4.1.zip)) qui devrait mieux marcher 😃

**Comment by laetitia-bos** [comment]
@Art-Ev ça fonctionne, merci beaucoup !

**Comment by Art-Ev** [comment]
@Orlenaafk, confirmation que le problème est bien résolu ?
