### ISSUE TITLE
Question pour l'étape 3 et 4 d'ICEtool

### ISSUE THREAD

**Issue by Wanair** [Art-Ev/ICEtool#28]
Bonjour,

Je poste cette question car je lance ICETool sur un projet et quelques soucis se présentent : 

- A l'étape 4, l'algorithme se termine normalement mais m'indique qu'il n'a pas pu générer les couches correctement en précisant que les couches en question sont "computed_points"

![image](https://github.com/Art-Ev/ICEtool/assets/131349009/f0bf963d-840b-494e-b404-eedf4769c331)

En chargeant à la main le computed_points_csv, j'arrive à visualiser les points de calcul sur mon projet. Je dois ensuite faire la symbologie.
J'avais déjà été jusqu'à l'étape 4 auparavant sur un autre projet et je n'avais pas besoin de faire la manipulation à la main, ça me chargeait la couche automatiquement avec la symbologie qui va avec. Sauriez-vous d'où pourrait venir ce problème ?

- A l'étape 3, les fichier tif qui en sortent commencent à "shadow_20220617_0600" dans mon cas et se terminent à "shadow_20220617_2100".
Je me demandais simplement si cela était correct ? Je ne suis pas censé avoir autant de fichiers que d'heures de la journée à savoir 24 ?

- Dans la table attributaire du fichier "computed_points_csv", j'ai des valeurs extrêmement élevées allant jusque 223 pour le max ou 127 pour la moyenne ce qui me semble être un soucis à cette étape. Auriez-vous une vision là-dessus ?
Est-ce que cela pourrait être lié au fait que les données météos soient faussées ? J'ai chargé moi-même des données Copernicus que j'ai converti pour "Global Horizontal Radiation" car elles étaient initialement en J/m².
Les données si cela aide : 
[WeatherData.csv](https://github.com/Art-Ev/ICEtool/files/14125135/WeatherData.csv)

Merci d'avance pour votre retour.
Erwan

**Comment by Art-Ev** [comment]
Bonjour,

1. Il doit y avoir un accent dans le chemin qui mène au fichier (surement un accent dans le nom du dossier de projet ou quelque chose de ressemblant)
2. Le nom semble correct. Seules les heures où le soleil est levé sont calculées (donc pas les 24 effectivement)
3. Effectivement valeurs anormales : j'ai déjà vu ça dans des cas où les polygones des matériaux étaient mal définis (le point d'échantillonnage "tombe" à un emplacement sans définition de matériau). Mais si le soucis est partout effectivement cela doit venir d'un problème d'unité dans les données météo, pas de fichier .epw directement disponible pour la zone étudiée ?

**Comment by Wanair** [comment]
Bonjour,

Merci pour votre retour rapide.

Concernant le point 1 effectivement, le chemin contient des accents, je vais les enlever et voir si cela modifie quelque chose.

Pour le point 3, j'avais récupéré un epw effectivement mais je voulais tester avec des données météo plus précise et surtout dans l'optique de pouvoir projeter à horizon plus lointain dans une autre simulation...
J'ai retenté avec un epw et les valeurs sont beaucoup plus cohérentes en effet donc je vais voir pour comprendre s'il y a un problème avec les données.

Pourriez-vous me redonner plus d'indication sur l'interpolation pour un rendu lisse dont vous aviez parlé sur un autre post ? Une extension en particulier que vous recommanderiez ?

**Comment by Art-Ev** [comment]
Pour l'interpolation : pas besoin d'extension, il suffit de chercher "interpolation" dans la boite à outil QGIS 😉 et prendre le temps de faire une recherche sur les 2 différentes méthodes pour comprendre les intérêts/limites de chacune (et donc choisir en fonction du cas d'usage).
Comme les autres sujets ont été à priori résolus je ferme le ticket !
