### ISSUE TITLE
Time series

### ISSUE THREAD

**Issue by FMARLIERE** [Art-Ev/ICEtool#8]
**Additional context**
Bonjour, serait-il possible d'expliquer comment réaliser une série temporelle à partir du résultat de l'étape 4 ? 
Merci pour cet incroyable plug-in :)

**Comment by Art-Ev** [comment]
Bonjour,
La problématique n'étant pas liée à ICEtool (création et configuration de champs), je clos le ticket et renvois 
au manuel de QGIS:
https://docs.qgis.org/3.16/en/docs/user_manual/index.html
Ou aux divers tutoriels disponibles:
https://www.qgistutorials.com/en/docs/3/animating_time_series.html
